import type { IntentTemplate, Scenario, ScenarioStep } from './types';

const step = (label: string, tpl: IntentTemplate, extra?: Partial<ScenarioStep>): ScenarioStep => ({
  label,
  tpl,
  ...extra,
});

export const SCENARIOS: Scenario[] = [
  {
    id: 'happy',
    name: '标准三方签署',
    desc: '员工 → 主管 → 外部合作方依次查阅、确认身份并签署，全程无故障。',
    steps: [
      step('发送信封', { type: 'send', actor: 'sender' }),
      step('员工查阅文件', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署', { type: 'sign', actor: 'employee' }),
      step('主管查阅', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管签署', { type: 'sign', actor: 'supervisor' }),
      step('合作方查阅', { type: 'view', actor: 'partner' }),
      step('合作方身份确认', { type: 'confirm_identity', actor: 'partner' }),
      step('合作方签署（完成）', { type: 'sign', actor: 'partner' }),
    ],
  },
  {
    id: 'order',
    name: '顺序冲突',
    desc: '主管试图抢在员工之前签署，被顺序守卫拒收；按正确顺序重试后放行。',
    steps: [
      step('发送信封', { type: 'send', actor: 'sender' }),
      step('主管查阅', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管抢先签署 → 被顺序守卫拒收', { type: 'sign', actor: 'supervisor' }),
      step('员工查阅', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署（第 1 顺位）', { type: 'sign', actor: 'employee' }),
      step('主管按序签署', { type: 'sign', actor: 'supervisor' }),
      step('合作方查阅', { type: 'view', actor: 'partner' }),
      step('合作方身份确认', { type: 'confirm_identity', actor: 'partner' }),
      step('合作方签署（完成）', { type: 'sign', actor: 'partner' }),
    ],
  },
  {
    id: 'replace',
    name: '补页换版',
    desc: '两人已签后文件补页：旧签名即时标记失效（而非提交时才发现），各方基于新指纹重签。',
    steps: [
      step('发送信封', { type: 'send', actor: 'sender' }),
      step('员工查阅 v1', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署 v1', { type: 'sign', actor: 'employee' }),
      step('主管查阅 v1', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管签署 v1', { type: 'sign', actor: 'supervisor' }),
      step('补页换版 v1 → v2（+2 页）', { type: 'replace_doc', actor: 'sender', note: '补充远程办公协议与风险披露' }),
      step('提交校验（演示旧系统视角）', { type: 'submit_check', actor: 'sender' }),
      step('员工重新查阅 v2', { type: 'view', actor: 'employee' }),
      step('员工重签 v2', { type: 'sign', actor: 'employee' }),
      step('主管重新查阅 v2', { type: 'view', actor: 'supervisor' }),
      step('主管重签 v2', { type: 'sign', actor: 'supervisor' }),
      step('合作方查阅 v2', { type: 'view', actor: 'partner' }),
      step('合作方身份确认', { type: 'confirm_identity', actor: 'partner' }),
      step('合作方签署（完成）', { type: 'sign', actor: 'partner' }),
    ],
  },
  {
    id: 'late',
    name: '晚到与重复回执',
    desc: '签署回执在途期间文件补页，到达即判作废；同一回执被重复投递，幂等忽略。',
    steps: [
      step('发送信封', { type: 'send', actor: 'sender' }),
      step('员工查阅 v1', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署（回执延迟 3 tick）', { type: 'sign', actor: 'employee' }, { lag: 3 }),
      step('补页换版 v1 → v2', { type: 'replace_doc', actor: 'sender', note: '补充风险披露' }),
      step('等待…', { type: 'wait', actor: 'system' }),
      step('等待（晚到回执到达 → 判作废）', { type: 'wait', actor: 'system' }),
      step('员工查阅 v2', { type: 'view', actor: 'employee' }),
      step('员工重签 v2（回执被重复投递）', { type: 'sign', actor: 'employee' }, { copies: 2 }),
      step('主管查阅', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管签署', { type: 'sign', actor: 'supervisor' }),
      step('合作方查阅', { type: 'view', actor: 'partner' }),
      step('合作方身份确认', { type: 'confirm_identity', actor: 'partner' }),
      step('合作方签署（完成）', { type: 'sign', actor: 'partner' }),
    ],
  },
  {
    id: 'withdraw',
    name: '撤回与重新发起',
    desc: '发件人撤回进行中的信封，晚到回执被拒收；重新发起生成新信封，旧签名不继承。',
    steps: [
      step('发送信封', { type: 'send', actor: 'sender' }),
      step('员工查阅', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署', { type: 'sign', actor: 'employee' }),
      step('主管查阅', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管签署（回执延迟 2 tick）', { type: 'sign', actor: 'supervisor' }, { lag: 2 }),
      step('发件人撤回信封', { type: 'withdraw', actor: 'sender' }),
      step('等待（晚到回执到达 → 已撤回拒收）', { type: 'wait', actor: 'system' }),
      step('重新发起（信封 #2）', { type: 'reinitiate', actor: 'sender' }),
      step('重新发送', { type: 'send', actor: 'sender' }),
      step('员工查阅', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署', { type: 'sign', actor: 'employee' }),
      step('主管查阅', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管签署', { type: 'sign', actor: 'supervisor' }),
      step('合作方查阅', { type: 'view', actor: 'partner' }),
      step('合作方身份确认', { type: 'confirm_identity', actor: 'partner' }),
      step('合作方签署（完成）', { type: 'sign', actor: 'partner' }),
    ],
  },
  {
    id: 'expire',
    name: '过期作废',
    desc: '签署拖延超过有效期，信封自动过期；迟到签署被拒，重新发起后完成。',
    steps: [
      step('发送信封', { type: 'send', actor: 'sender' }),
      step('员工查阅', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('等待 25 tick（超过有效期 → 自动过期）', { type: 'wait', actor: 'system' }, { advance: 25 }),
      step('员工迟到签署 → 已过期拒收', { type: 'sign', actor: 'employee' }),
      step('重新发起（信封 #2）', { type: 'reinitiate', actor: 'sender' }),
      step('重新发送', { type: 'send', actor: 'sender' }),
      step('员工查阅', { type: 'view', actor: 'employee' }),
      step('员工身份确认', { type: 'confirm_identity', actor: 'employee' }),
      step('员工签署', { type: 'sign', actor: 'employee' }),
      step('主管查阅', { type: 'view', actor: 'supervisor' }),
      step('主管身份确认', { type: 'confirm_identity', actor: 'supervisor' }),
      step('主管签署', { type: 'sign', actor: 'supervisor' }),
      step('合作方查阅', { type: 'view', actor: 'partner' }),
      step('合作方身份确认', { type: 'confirm_identity', actor: 'partner' }),
      step('合作方签署（完成）', { type: 'sign', actor: 'partner' }),
    ],
  },
];
